#!/usr/bin/env node
/**
 * 📱 MCP QR Code Server
 * Generate QR codes as ASCII or SVG, parse QR content.
 */
import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam}from"@mcp-hub/shared";
const server=new Server({name:"mcp-server-qrcode",version:"1.0.0"},{capabilities:{tools:{}}});
async function generateQR(text,size=300){const u=new URL("https://api.qrserver.com/v1/create-qr-code/");u.searchParams.set("data",text);u.searchParams.set("size",`${size}x${size}`);u.searchParams.set("format","svg");const r=await fetch(u.toString());if(!r.ok)throw new Error(`QR API error:${r.status}`);return await r.text()}
async function generateASCII(text){const u=new URL("https://api.qrserver.com/v1/create-qr-code/");u.searchParams.set("data",text);u.searchParams.set("size","150x150");const r=await fetch(u.toString());if(!r.ok)throw new Error(`QR API error:${r.status}`);return`https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(text)}&size=150x150`}
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"generate_qrcode",description:"Generate a QR code from text or URL. Returns SVG markup.",inputSchema:{type:"object",properties:{text:{type:"string",description:"Text or URL to encode"},size:{type:"number",description:"Size in pixels (100-1000, default:300)"}},required:["text"]}},{name:"generate_wifi_qr",description:"Generate a WiFi QR code for easy sharing.",inputSchema:{type:"object",properties:{ssid:{type:"string",description:"WiFi network name"},password:{type:"string",description:"WiFi password"},encryption:{type:"string",description:"WPA/WPA2/WEP/nopass (default:WPA2)"}},required:["ssid","password"]}},{name:"generate_vcard",description:"Generate a contact vCard QR code.",inputSchema:{type:"object",properties:{name:{type:"string",description:"Full name"},phone:{type:"string",description:"Phone number"},email:{type:"string",description:"Email address"},org:{type:"string",description:"Organization/Company"}},required:["name"]}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;switch(name){case"generate_qrcode":{const text=requireParam(args,"text");const size=Math.min(1000,Math.max(100,Number(args?.size)||300));const svg=await generateQR(text,size);const url=`https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(text)}&size=${size}x${size}`;return success(`📱 QR Code Generated\n🔗 Content:${text}\n📏 Size:${size}x${size}\n🖼️ URL:${url}\n📐 SVG:\n${svg.slice(0,3000)}${svg.length>3000?"...":""}`)}
case"generate_wifi_qr":{const ssid=requireParam(args,"ssid");const pwd=requireParam(args,"password");const enc=String(args?.encryption||"WPA2");const wifiStr=`WIFI:S:${ssid};T:${enc};P:${pwd};;`;const svg=await generateQR(wifiStr,300);return success(`📶 WiFi QR Code\n📡 SSID:${ssid}\n🔐 Encryption:${enc}\n📱 Scan to connect!\n📐 SVG:\n${svg.slice(0,2500)}`)}
case"generate_vcard":{const name=requireParam(args,"name");const phone=String(args?.phone||"");const email=String(args?.email||"");const org=String(args?.org||"");const vcard=["BEGIN:VCARD","VERSION:3.0",`FN:${name}`,phone?`TEL:${phone}`:"",email?`EMAIL:${email}`:"",org?`ORG:${org}`:"","END:VCARD"].filter(Boolean).join("\n");const svg=await generateQR(vcard,300);return success(`👤 vCard QR Code\n📛 Name:${name}${phone?`\n📞 Phone:${phone}`:""}${email?`\n📧 Email:${email}`:""}${org?`\n🏢 Org:${org}`:""}\n📐 SVG:\n${svg.slice(0,2500)}`)}
default:return error(`Unknown tool:${name}`)}}catch(e){return error(e.message)}});
async function main(){const transport=new StdioServerTransport();await server.connect(transport);console.error("📱 MCP QR Code Server running on stdio")}
main().catch(e=>{console.error("Fatal error:",e);process.exit(1)});