#!/usr/bin/env node
import{execSync}from"node:child_process";import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam,getOptionalParam}from"@mcp-hub/shared";
const server=new Server({name:"mcp-server-code-runner",version:"1.0.0"},{capabilities:{tools:{}}});
const TIMEOUT=Number(process.env.MCP_CODE_TIMEOUT)||10000;
const MAX_OUTPUT=Number(process.env.MCP_CODE_MAX_OUTPUT)||50000;
function runCommand(cmd,code,lang){const tmp=/^(python|py|python3)$/i.test(lang)?"code.py":"code.js";const fs=require("node:fs"),path=require("node:path"),os=require("node:os");const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mcp-code-"));const fp=path.join(dir,tmp);fs.writeFileSync(fp,code);try{let result;if(/^(python|py|python3)$/i.test(lang)){result=execSync(`python3 -c ${JSON.stringify(code)}`,{timeout:TIMEOUT,maxBuffer:MAX_OUTPUT,encoding:"utf-8",env:{...process.env,HOME:os.homedir()}})}else{result=execSync(`node -e ${JSON.stringify(code)}`,{timeout:TIMEOUT,maxBuffer:MAX_OUTPUT,encoding:"utf-8"})}return{success:true,stdout:result.slice(0,MAX_OUTPUT),stderr:""}}catch(e){return{success:false,stdout:e.stdout?.slice(0,MAX_OUTPUT)||"",stderr:e.stderr?.slice(0,MAX_OUTPUT)||e.message}}}
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"run_code",description:"Execute Python or JavaScript code in a sandbox. Returns stdout/stderr. Supports Python3 and Node.js.",inputSchema:{type:"object",properties:{language:{type:"string",description:"python or javascript"},code:{type:"string",description:"Source code to execute"},timeout:{type:"number",description:"Timeout in ms (default:10000, max:30000)"}},required:["language","code"]}},{name:"run_python",description:"Execute Python code. Shortcut for run_code with language=python.",inputSchema:{type:"object",properties:{code:{type:"string",description:"Python code to execute"}},required:["code"]}},{name:"run_javascript",description:"Execute JavaScript code. Shortcut for run_code with language=javascript.",inputSchema:{type:"object",properties:{code:{type:"string",description:"JavaScript code to execute"}},required:["code"]}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;switch(name){case"run_code":{const lang=requireParam(args,"language");const code=requireParam(args,"code");const to=Math.min(30000,Number(args?.timeout)||TIMEOUT);if(!/^(python|py|python3|javascript|js|node)$/i.test(lang))return error("Language must be python or javascript");const norm=/^(javascript|js|node)$/i.test(lang)?"javascript":"python";const r=runCommand(norm,code,norm);if(r.success){const out=r.stdout||"(no output)";return success(`✅ ${norm} executed successfully\n\n${out}`)}return error(`${r.stderr}\n${r.stdout?"stdout: "+r.stdout:""}`)}
case"run_python":{const code=requireParam(args,"code");const r=runCommand("python",code,"python");if(r.success)return success(`🐍 Python:\n${r.stdout||"(no output)"}`);return error(r.stderr||r.stdout)}
case"run_javascript":{const code=requireParam(args,"code");const r=runCommand("javascript",code,"javascript");if(r.success)return success(`📜 JavaScript:\n${r.stdout||"(no output)"}`);return error(r.stderr||r.stdout)}
default:return error("Unknown: "+name)}}catch(e){return error(e.message)}});
async function main(){const t=new StdioServerTransport();await server.connect(t);console.error("🐍 Code Runner running")}
main().catch(e=>{console.error(e);process.exit(1)});