import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam}from"@mcp-hub/shared";
const s=new Server({name:"mcp-server-web-search",version:"2.0.1"},{capabilities:{tools:{}}});
function decodeUrl(href){try{if(href.includes("uddg=")){const m=href.match(/uddg=([^&]+)/);if(m)return decodeURIComponent(m[1])}}catch{}return href.replace(/&amp;/g,"&")}
async function search(q,n){const u="https://html.duckduckgo.com/html/?q="+encodeURIComponent(q);const r=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw new Error("HTTP "+r.status);const h=await r.text();const res=[];const lr=/<a[^>]*class="result__a"[^>]*href="([^"]+)"[^>]*>([^<]+)<\/a>/gi;const sr=/<a[^>]*class="result__snippet"[^>]*>([^<]+(?:<[^>]+>[^<]*)*)<\/a>/gi;let m;const links=[];while((m=lr.exec(h))!==null&&links.length<n)links.push({t:m[2].replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim(),u:decodeUrl(m[1])});const sn=[];while((m=sr.exec(h))!==null)sn.push(m[1].replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").trim());for(let i=0;i<Math.min(links.length,sn.length,n);i++)res.push({title:links[i].t,url:links[i].u,snippet:sn[i]||""});return res}
s.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"web_search",description:"Search the web via DuckDuckGo. Returns real URLs.",inputSchema:{type:"object",properties:{query:{type:"string"},count:{type:"number"}},required:["query"]}},{name:"search_news",description:"Search recent news articles on a topic.",inputSchema:{type:"object",properties:{query:{type:"string"},count:{type:"number"}},required:["query"]}},{name:"fetch_page",description:"Extract readable text from a URL.",inputSchema:{type:"object",properties:{url:{type:"string"},max_chars:{type:"number"}},required:["url"]}},{name:"search_site",description:"Search within a specific domain (site: operator).",inputSchema:{type:"object",properties:{site:{type:"string"},query:{type:"string"},count:{type:"number"}},required:["site","query"]}}]}));
s.setRequestHandler(CallToolRequestSchema,async(req)=>{try{const{name,arguments:a}=req.params;switch(name){case"web_search":{const q=requireParam(a,"query");const n=Math.min(20,Number(a?.count)||10);const r=await search(q,n);if(!r.length)return success("No results for: "+q);const l=["Search: "+q,"",r.length+" results:"];r.forEach((x,i)=>l.push("["+(i+1)+"] "+x.title+"\n    "+x.url+(x.snippet?"\n    "+x.snippet:"")));return success(l.join("\n\n"))}
case"search_news":{const q=requireParam(a,"query");const n=Math.min(15,Number(a?.count)||8);const r=await search(q+" news",n);const l=["News: "+q,"",r.length+" results:"];r.forEach((x,i)=>l.push("["+(i+1)+"] "+x.title+"\n    "+x.url));return success(l.join("\n\n"))}
case"fetch_page":{const u=requireParam(a,"url");const mc=Number(a?.max_chars)||5000;const r=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw new Error("HTTP "+r.status);let t=(await r.text()).replace(/<script[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();if(t.length>mc)t=t.slice(0,mc)+"...";return success("Page: "+u+"\n\n"+t)}
case"search_site":{const si=requireParam(a,"site");const q=requireParam(a,"query");const n=Math.min(15,Number(a?.count)||8);const r=await search("site:"+si+" "+q,n);const l=["Site: "+si+" \""+q+"\"","",r.length+" results:"];r.forEach((x,i)=>l.push("["+(i+1)+"] "+x.title+"\n    "+x.url));return success(l.join("\n\n"))}
default:return error("Unknown: "+name)}}catch(e){return error(e.message)}});
async function main(){const t=new StdioServerTransport();await s.connect(t);console.error("Web Search v2.1 running")}
main().catch(e=>{console.error(e);process.exit(1)});