#!/usr/bin/env node
import*as fs from"node:fs";import*as path from"node:path";import*as os from"node:os";import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam,getOptionalParam}from"@mcp-hub/shared";
const DB=process.env.MCP_MEMORY_PATH||path.join(os.homedir(),".mcp-memory.json");const server=new Server({name:"mcp-server-memory",version:"2.0.0"},{capabilities:{tools:{}}});
interface Entry{key:string;value:string;tags:string[];ttl:number;createdAt:number;updatedAt:number}
function load(){try{if(fs.existsSync(DB))return JSON.parse(fs.readFileSync(DB,"utf-8"))}catch{}return{}}
function save(db:Record<string,Entry>){const d=path.dirname(DB);if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});fs.writeFileSync(DB,JSON.stringify(db,null,2))}
function ts(){return Math.floor(Date.now()/1000)}
function isExp(e:Entry){return e.ttl>0&&(e.createdAt+e.ttl)<ts()}

// ── Semantic/Smart Search ────────────────────────────
function tokenize(t:string):string[]{return t.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g," ").split(/\s+/).filter(w=>w.length>1)}
function relevanceScore(query:string,entry:Entry):number{const qTokens=tokenize(query);if(!qTokens.length)return 0;let score=0;const keyLower=entry.key.toLowerCase();const valLower=entry.value.toLowerCase();qTokens.forEach(t=>{if(keyLower===t)score+=3;else if(keyLower.includes(t))score+=2;if(valLower.includes(t))score+=1;const exactInVal=(valLower.match(new RegExp("\\b"+t+"\\b","g"))||[]).length;score+=exactInVal*0.5});const tagMatch=entry.tags.some(tag=>qTokens.some(qt=>tag.toLowerCase().includes(qt)||qt.includes(tag.toLowerCase())));if(tagMatch)score+=2;const recency=Math.max(0,1-(ts()-entry.updatedAt)/(86400*30));score+=recency*0.5;return Math.round(score*100)/100}

server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"memory_set",description:"Store value with key. Supports TTL (seconds), tags, and auto-categorization.",inputSchema:{type:"object",properties:{key:{type:"string"},value:{type:"string"},ttl:{type:"number",description:"TTL seconds, 0=forever"},tags:{type:"string",description:"Comma-separated tags"}},required:["key","value"]}},{name:"memory_get",description:"Get exact value by key.",inputSchema:{type:"object",properties:{key:{type:"string"}},required:["key"]}},{name:"memory_search",description:"🔍 Semantic/relevance search across all memory. Returns scored results sorted by relevance.",inputSchema:{type:"object",properties:{query:{type:"string",description:"Search query - matches keys, values, and tags"},limit:{type:"number",description:"Max results (default:10)"},min_score:{type:"number",description:"Minimum relevance score (default:0.5)"}},required:["query"]}},{name:"memory_context",description:"🤖 RAG-lite: retrieve most relevant memories as context for AI. Ideal for injecting into prompts.",inputSchema:{type:"object",properties:{query:{type:"string",description:"What context do you need?"},limit:{type:"number",description:"Max memories (default:5)"}},required:["query"]}},{name:"memory_list",description:"List entries with optional sort (relevance/recent/alpha).",inputSchema:{type:"object",properties:{tag:{type:"string"},search:{type:"string"},sort:{type:"string",description:"Sort: recent (default), alpha"},limit:{type:"number",description:"Max entries (default:50)"}}}},{name:"memory_delete",description:"Delete entry by key.",inputSchema:{type:"object",properties:{key:{type:"string"}},required:["key"]}},{name:"memory_tags",description:"List all tags with counts.",inputSchema:{type:"object",properties:{}}},{name:"memory_export",description:"Export all memories as JSON.",inputSchema:{type:"object",properties:{path:{type:"string",description:"Optional output file path"}}}},{name:"memory_import",description:"Import memories from JSON string or file.",inputSchema:{type:"object",properties:{json:{type:"string",description:"JSON string of memories ({\\"key\\":{...}})"},file:{type:"string",description:"OR: path to JSON file"},merge:{type:"boolean",description:"Merge (true) or replace (false, default:merge)"}},required:[]}},{name:"memory_stats",description:"Show memory statistics.",inputSchema:{type:"object",properties:{}}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;const db=load();switch(name){case"memory_set":{const k=requireParam(args,"key");const v=requireParam(args,"value");const ttl=Number(args?.ttl)||0;const tags=(args?.tags||"").split(",").map((t:string)=>t.trim()).filter(Boolean);const t=ts();const old=db[k];db[k]={key:k,value:v,tags,ttl,createdAt:old?.createdAt||t,updatedAt:t};save(db);return success("🧠 Stored: "+k+"\n📝 "+v.slice(0,200)+(v.length>200?"...":"")+"\n⏱️ "+(ttl?ttl+"s":"forever")+"\n🏷️ "+(tags.join(", ")||"none"))}
case"memory_get":{const k=requireParam(args,"key");const e=db[k];if(!e)return success("🔍 Not found: "+k);if(isExp(e)){delete db[k];save(db);return success("⏰ Expired: "+k)}return success("🧠 "+k+"\n📝 "+e.value+"\n📅 "+new Date(e.createdAt*1000).toISOString()+"\n🏷️ "+(e.tags.join(", ")||"none"))}
case"memory_search":{const q=requireParam(args,"query");const lim=Math.min(50,Number(args?.limit)||10);const minS=Number(args?.min_score)||0.5;let results=Object.values(db).filter(e=>!isExp(e)).map(e=>({...e,score:relevanceScore(q,e)})).filter(e=>e.score>=minS);results.sort((a,b)=>b.score-a.score);const top=results.slice(0,lim);if(!top.length)return success("🔍 No results for: "+q+"\n💡 Try different keywords.");const lines=["🔍 Search: "+q,"📊 "+top.length+" results (min score "+minS+"):",""];top.forEach((r,i)=>{lines.push("["+(i+1)+"] "+r.key+" (score: "+r.score+")"+((r as any).tags?.length?" ["+(r as any).tags.join(", ")+"]":""));lines.push("    "+r.value.slice(0,150)+(r.value.length>150?"...":""));lines.push("")});return success(lines.join("\n"))}
case"memory_context":{const q=requireParam(args,"query");const lim=Math.min(10,Number(args?.limit)||5);let results=Object.values(db).filter(e=>!isExp(e)).map(e=>({...e,score:relevanceScore(q,e)}));results.sort((a,b)=>b.score-a.score);const top=results.slice(0,lim).filter(e=>e.score>0);if(!top.length)return success("No relevant memories found.");const ctx=top.map(r=>"["+r.key+"]: "+r.value).join("\n\n");return success("🤖 Context ("+top.length+" memories):\n\n"+ctx.slice(0,8000))}
case"memory_list":{const tag=(args?.tag||"").toLowerCase();const q=(args?.search||"").toLowerCase();const sort=args?.sort||"recent";let entries=Object.values(db).filter(e=>!isExp(e));if(tag)entries=entries.filter(e=>e.tags.some(t=>t.toLowerCase()===tag));if(q)entries=entries.filter(e=>e.key.toLowerCase().includes(q)||e.value.toLowerCase().includes(q));if(sort==="alpha")entries.sort((a,b)=>a.key.localeCompare(b.key));else entries.sort((a,b)=>b.updatedAt-a.updatedAt);const lim=Number(args?.limit)||50;const lines=["🧠 Memory ("+entries.length+" entries)"+(tag?" ["+tag+"]":"")];entries.slice(0,lim).forEach((e,i)=>{lines.push((i+1)+". "+e.key+(e.tags.length?" ["+e.tags.join(", ")+"]":""));lines.push("   "+e.value.slice(0,100)+(e.value.length>100?"...":""))});if(entries.length>lim)lines.push("... and "+(entries.length-lim)+" more");return success(lines.join("\n"))}
case"memory_delete":{const k=requireParam(args,"key");const ok=!!db[k];delete db[k];save(db);return success(ok?"🗑️ "+k:"🔍 Not found: "+k)}
case"memory_tags":{const tagMap:Record<string,number>={};Object.values(db).filter(e=>!isExp(e)).forEach(e=>e.tags.forEach(t=>{tagMap[t]=(tagMap[t]||0)+1}));const tags=Object.entries(tagMap).sort((a,b)=>b[1]-a[1]);return success("🏷️ Tags ("+tags.length+"):\n"+tags.map(([t,n])=>("  #"+t+" ("+n+")")).join("\n")||"  (no tags)")}
case"memory_export":{const data=JSON.stringify(db,null,2);const outPath=args?.path;if(outPath){fs.writeFileSync(outPath,data);return success("📤 Exported "+Object.keys(db).length+" entries to "+outPath)}return success("📤 Export ("+Object.keys(db).length+" entries):\n"+data.slice(0,10000)+(data.length>10000?"\n... truncated":""))}
case"memory_import":{const merge=args?.merge!==false;let data:Record<string,Entry>={};if(args?.file){if(!fs.existsSync(args.file))return error("File not found: "+args.file);data=JSON.parse(fs.readFileSync(args.file,"utf-8"))}else if(args?.json){data=JSON.parse(args.json)}else{return error("Provide json string or file path")}
const count=Object.keys(data).length;if(merge){const merged={...db,...data};save(merged)}else{save(data)}
return success("📥 Imported "+count+" entries"+(merge?" (merged)":" (replaced)"))}
case"memory_stats":{const entries=Object.values(db);const active=entries.filter(e=>!isExp(e));const expired=entries.length-active.length;const tagCount=new Set(active.flatMap(e=>e.tags)).size;const totalSize=JSON.stringify(db).length;return success("📊 Memory Stats\n📝 Total: "+entries.length+"\n✅ Active: "+active.length+"\n⏰ Expired: "+expired+"\n🏷️ Tags: "+tagCount+"\n💾 Size: "+(totalSize<1024?totalSize+" B":totalSize<1048576?(totalSize/1024).toFixed(1)+" KB":(totalSize/1048576).toFixed(1)+" MB")+"\n📁 Path: "+DB)}
default:return error("Unknown: "+name)}}catch(e:any){return error(e.message)}});
async function main(){const t=new StdioServerTransport();await server.connect(t);console.error("🧠 Memory v2 running ("+DB+")")}
main().catch(e=>{console.error(e);process.exit(1)});