#!/usr/bin/env node
import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam}from"@mcp-hub/shared";
const server=new Server({name:"mcp-server-rss",version:"1.0.0"},{capabilities:{tools:{}}});
async function fetchFeed(url){const resp=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (compatible; MCPBot/1.0)"}});if(!resp.ok)throw new Error("HTTP "+resp.status);const xml=await resp.text();const items=[];const re=/<item>([\s\S]*?)<\/item>/gi;let m;while((m=re.exec(xml))!==null){const b=m[1];items.push({title:getTag(b,"title"),link:getTag(b,"link"),pubDate:getTag(b,"pubDate"),desc:cleanHtml(getTag(b,"description")).slice(0,300)})}
const cm=xml.match(/<title>([^<]+)<\/title>/);return{title:cm?cm[1].replace(/<![\\[]CDATA[|[]]>/g,""):"Feed",items}}
function getTag(x,t){const r=new RegExp("<"+t+"[^>]*>([\\s\\S]*?)</"+t+">","i");const m=x.match(r);return m?m[1].replace(/<![\\[]CDATA[|[]]>/g,"").trim():""}
function cleanHtml(h){return h.replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim()}
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"fetch_feed",description:"Fetch and parse RSS/Atom feed.",inputSchema:{type:"object",properties:{url:{type:"string",description:"Feed URL"},count:{type:"number",description:"Max items (default:10)"}},required:["url"]}},{name:"discover_feed",description:"Discover RSS feeds from a website.",inputSchema:{type:"object",properties:{url:{type:"string",description:"Website URL"}},required:["url"]}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;switch(name){case"fetch_feed":{const u=requireParam(args,"url");const n=Math.min(50,Number(args?.count)||10);const{title,items}=await fetchFeed(u);const l=["📡 "+title,"🔗 "+u,""];items.slice(0,n).forEach((it,i)=>{l.push("["+(i+1)+"] "+it.title);l.push("    🔗 "+it.link);if(it.pubDate)l.push("    📅 "+it.pubDate);if(it.desc)l.push("    📝 "+it.desc);l.push("")});return success(l.join("\n"))}
case"discover_feed":{const u=requireParam(args,"url");const resp=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0"}});if(!resp.ok)throw new Error("HTTP "+resp.status);const html=await resp.text();const feeds=[];const lr=/<link[^>]*type="application\/(rss|atom)\+xml"[^>]*href="([^"]+)"/gi;let m;while((m=lr.exec(html))!==null){let h=m[2];if(h.startsWith("/")){const pu=new URL(u);h=pu.origin+h}feeds.push(h)}if(!feeds.length)return success("🔍 No feeds found at "+u);return success("📡 Found "+feeds.length+" feed(s):\n"+feeds.map(f=>"  🔗 "+f).join("\n"))}
default:return error("Unknown tool: "+name)}}catch(e){return error(e.message)}});
async function main(){const t=new StdioServerTransport();await server.connect(t);console.error("📡 RSS Server running")}
main().catch(e=>{console.error(e);process.exit(1)});