#!/usr/bin/env node
import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam,getOptionalParam}from"@mcp-hub/shared";
const server=new Server({name:"mcp-server-fetch",version:"1.0.0"},{capabilities:{tools:{}}});
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"fetch",description:"Make an HTTP request. Supports GET/POST/PUT/DELETE/PATCH with custom headers and body.",inputSchema:{type:"object",properties:{url:{type:"string",description:"URL to fetch"},method:{type:"string",description:"HTTP method: GET/POST/PUT/DELETE/PATCH (default:GET)"},headers:{type:"string",description:"JSON string of headers, e.g. '{\\"Content-Type\\":\\"application/json\\"}'"},body:{type:"string",description:"Request body (for POST/PUT/PATCH)"},timeout:{type:"number",description:"Timeout in ms (default:15000)"}},required:["url"]}},{name:"fetch_json",description:"Fetch JSON from an API. Auto-parses response as JSON.",inputSchema:{type:"object",properties:{url:{type:"string",description:"API URL"},method:{type:"string",description:"HTTP method (default:GET)"},headers:{type:"string",description:"JSON headers string"},body:{type:"string",description:"JSON body string"}},required:["url"]}},{name:"check_url",description:"Check if a URL is reachable (HEAD request). Returns status code.",inputSchema:{type:"object",properties:{url:{type:"string",description:"URL to check"}},required:["url"]}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;switch(name){case"fetch":{const url=requireParam(args,"url");const method=(args?.method||"GET").toUpperCase();const to=Number(args?.timeout)||15000;let hdrs:Record<string,string>={};if(args?.headers)try{hdrs=JSON.parse(args.headers)}catch{return error("Invalid headers JSON")}
const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),to);try{const opts:RequestInit={method,headers:hdrs,signal:ctrl.signal};if(args?.body&&method!=="GET")opts.body=args.body;const resp=await fetch(url,opts);clearTimeout(t);const ct=resp.headers.get("content-type")||"";const isText=ct.includes("text")||ct.includes("json")||ct.includes("xml")||ct.includes("javascript");let body="";if(isText){body=await resp.text();if(body.length>10000)body=body.slice(0,10000)+`\n... (truncated, ${body.length-10000} more chars)`}else{const blob=await resp.arrayBuffer();body=`[Binary: ${blob.byteLength} bytes, ${ct}]`}
const hdrStr=Array.from(resp.headers.entries()).map(([k,v])=>`${k}: ${v}`).join("\n");return success(`🌐 ${method} ${url}\n📊 Status: ${resp.status} ${resp.statusText}\n📋 Headers:\n${hdrStr.slice(0,2000)}\n\n📄 Body:\n${body}`)}catch(e:any){clearTimeout(t);if(e.name==="AbortError")return error(`Timeout after ${to}ms`);throw e}}
case"fetch_json":{const url=requireParam(args,"url");const method=(args?.method||"GET").toUpperCase();let hdrs:Record<string,string>={Accept:"application/json"};if(args?.headers)try{hdrs={...hdrs,...JSON.parse(args.headers)}}catch{return error("Invalid headers JSON")}
const opts:RequestInit={method,headers:hdrs};if(args?.body&&method!=="GET"){opts.body=args.body;if(!hdrs["Content-Type"])hdrs["Content-Type"]="application/json"}
const resp=await fetch(url,opts);const json=await resp.json();const pretty=JSON.stringify(json,null,2);return success(`🌐 ${method} ${url}\n📊 ${resp.status}\n\n📋 JSON:\n${pretty.slice(0,8000)}${pretty.length>8000?"\n...":""}`)}
case"check_url":{const url=requireParam(args,"url");const start=Date.now();try{const resp=await fetch(url,{method:"HEAD",signal:AbortSignal.timeout(10000)});return success(`✅ ${url}\n📊 ${resp.status} ${resp.statusText}\n⏱️ ${Date.now()-start}ms`)}catch(e:any){return success(`❌ ${url}\n📊 Error: ${e.message}\n⏱️ ${Date.now()-start}ms`)}}
default:return error("Unknown: "+name)}}catch(e){return error(e.message)}});
async function main(){const t=new StdioServerTransport();await server.connect(t);console.error("🌐 Fetch Server running")}
main().catch(e=>{console.error(e);process.exit(1)});