#!/usr/bin/env node
/**
 * 📚 MCP Knowledge Server v1
 * RAG-lite: document ingestion, chunking, keyword retrieval.
 * Zero external dependencies - pure TF-IDF-like scoring.
 */
import*as fs from"node:fs";import*as path from"node:path";import*as os from"node:os";import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam}from"@mcp-hub/shared";
const DB=process.env.MCP_KNOWLEDGE_PATH||path.join(os.homedir(),".mcp-knowledge.json");
const server=new Server({name:"mcp-server-knowledge",version:"1.0.0"},{capabilities:{tools:{}}});
interface Doc{id:string;title:string;content:string;chunks:Chunk[];source:string;createdAt:number}
interface Chunk{id:string;text:string;index:number}
function load():Record<string,Doc>{try{if(fs.existsSync(DB))return JSON.parse(fs.readFileSync(DB,"utf-8"))}catch{}return{}}
function save(db:Record<string,Doc>){const d=path.dirname(DB);if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});fs.writeFileSync(DB,JSON.stringify(db,null,2))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function chunkText(text:string,size=500):Chunk[]{const words=text.split(/\s+/);const chunks:Chunk[]=[];for(let i=0;i<words.length;i+=Math.floor(size/2)){const c=words.slice(i,i+size).join(" ");if(c.trim().length>20)chunks.push({id:uid(),text:c,index:chunks.length})}return chunks}

// TF-IDF-like keyword scoring
function tokenize(text:string):string[]{return text.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g," ").split(/\s+/).filter(w=>w.length>1)}
function scoreChunk(query:string,chunk:string):number{const qTokens=new Set(tokenize(query));const cTokens=tokenize(chunk);if(!qTokens.size||!cTokens.length)return 0;let hits=0;const seen=new Set<string>();for(const w of cTokens){if(qTokens.has(w)&&!seen.has(w)){hits++;seen.add(w)}}
const jaccard=hits/(qTokens.size+cTokens.length-hits);const density=hits/cTokens.length;return jaccard*0.5+density*0.3+(hits/qTokens.size)*0.2}

server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"ingest_text",description:"Ingest a text document. Splits into chunks for retrieval. Returns document ID.",inputSchema:{type:"object",properties:{title:{type:"string",description:"Document title"},content:{type:"string",description:"Full text content"},source:{type:"string",description:"Source/origin label"}},required:["title","content"]}},{name:"ingest_file",description:"Ingest a local text file (.txt/.md/.json/.csv).",inputSchema:{type:"object",properties:{path:{type:"string",description:"File path"},title:{type:"string",description:"Optional title (default:filename)"}},required:["path"]}},{name:"retrieve",description:"Retrieve relevant chunks from all documents. Returns top-k scored results.",inputSchema:{type:"object",properties:{query:{type:"string",description:"Search query"},top_k:{type:"number",description:"Number of results (default:5)"},min_score:{type:"number",description:"Minimum relevance score 0-1 (default:0.05)"}},required:["query"]}},{name:"list_docs",description:"List all ingested documents.",inputSchema:{type:"object",properties:{}}},{name:"get_doc",description:"Get full document content by ID.",inputSchema:{type:"object",properties:{id:{type:"string"}},required:["id"]}},{name:"delete_doc",description:"Delete a document by ID.",inputSchema:{type:"object",properties:{id:{type:"string"}},required:["id"]}},{name:"search_docs",description:"Search across document titles and sources.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"]}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;const db=load();switch(name){case"ingest_text":{const title=requireParam(args,"title");const content=requireParam(args,"content");const source=String(args?.source||"manual");const id=uid();const chunks=chunkText(content);db[id]={id,title,content,chunks,source,createdAt:Date.now()};save(db);return success("📚 Ingested: "+title+"\n🆔 "+id+"\n📝 "+content.length+" chars\n🧩 "+chunks.length+" chunks\n📎 "+source)}
case"ingest_file":{const fp=requireParam(args,"path");if(!fs.existsSync(fp))return error("File not found: "+fp);const stat=fs.statSync(fp);if(stat.size>5*1024*1024)return error("File too large (>5MB)");const content=fs.readFileSync(fp,"utf-8");const title=String(args?.title||path.basename(fp));const id=uid();const chunks=chunkText(content);db[id]={id,title,content,chunks,source:"file:"+fp,createdAt:Date.now()};save(db);return success("📄 Ingested: "+title+"\n🆔 "+id+"\n📝 "+content.length+" chars\n🧩 "+chunks.length+" chunks")}
case"retrieve":{const query=requireParam(args,"query");const topK=Math.min(20,Number(args?.top_k)||5);const minScore=Number(args?.min_score)||0.05;const results:any[]=[];Object.values(db).forEach(doc=>{doc.chunks.forEach(chunk=>{const score=scoreChunk(query,chunk.text);if(score>=minScore)results.push({docId:doc.id,title:doc.title,chunkIndex:chunk.index,text:chunk.text.slice(0,600),score:Math.round(score*1000)/1000})})});results.sort((a,b)=>b.score-a.score);const top=results.slice(0,topK);if(!top.length)return success("🔍 No relevant results for: "+query+"\n💡 Try broader keywords.");const lines=["🔍 Query: "+query,"📊 "+top.length+" results (top "+topK+"):",""];top.forEach((r,i)=>{lines.push("["+(i+1)+"] "+r.title+" (score: "+r.score+")");lines.push("    "+r.text.slice(0,200)+(r.text.length>200?"...":""));lines.push("")});return success(lines.join("\n"))}
case"list_docs":{const docs=Object.values(db).sort((a,b)=>b.createdAt-a.createdAt);const lines=["📚 Documents ("+docs.length+"):",""];docs.forEach(d=>lines.push("  🆔 "+d.id.slice(0,8)+"...  📄 "+d.title+"  🧩 "+d.chunks.length+" chunks  📅 "+new Date(d.createdAt).toISOString().slice(0,10)));return success(lines.join("\n"))}
case"get_doc":{const id=requireParam(args,"id");const doc=Object.values(db).find(d=>d.id.startsWith(id));if(!doc)return error("Document not found: "+id);const preview=doc.content.slice(0,3000)+(doc.content.length>3000?"\n... ("+(doc.content.length-3000)+" more chars)":"");return success("📄 "+doc.title+"\n🆔 "+doc.id+"\n📎 "+doc.source+"\n📝 "+doc.content.length+" chars, "+doc.chunks.length+" chunks\n📅 "+new Date(doc.createdAt).toISOString()+"\n\n"+preview)}
case"delete_doc":{const id=requireParam(args,"id");const match=Object.entries(db).find(([k])=>k.startsWith(id));if(!match)return error("Not found: "+id);const[docId,doc]=match;delete db[docId];save(db);return success("🗑️ Deleted: "+doc.title+" ("+docId+")")}
case"search_docs":{const q=requireParam(args,"query").toLowerCase();const docs=Object.values(db).filter(d=>d.title.toLowerCase().includes(q)||d.source.toLowerCase().includes(q)||d.content.slice(0,500).toLowerCase().includes(q));const lines=["🔍 '"+q+"' - "+docs.length+" match(es):",""];docs.forEach(d=>lines.push("  📄 "+d.title+" ("+d.id.slice(0,8)+"...)"));return success(lines.join("\n"))}
default:return error("Unknown: "+name)}}catch(e:any){return error(e.message)}});
async function main(){const t=new StdioServerTransport();await server.connect(t);console.error("📚 Knowledge Server running ("+DB+")")}
main().catch(e=>{console.error(e);process.exit(1)});