#!/usr/bin/env node
import*as os from"node:os";import*as path from"node:path";
const R=[{name:"weather",package:"@mcp-hub/server-weather",emoji:"🌤️",desc:"Weather forecast, current conditions, air quality",tools:["get_forecast","get_current","get_air_quality"],key:false},{name:"translator",package:"@mcp-hub/server-translator",emoji:"🌍",desc:"Multi-language translation, language detection",tools:["translate","list_languages","detect_language"],key:false},{name:"filesystem",package:"@mcp-hub/server-filesystem",emoji:"📁",desc:"Safe file read/write/list/search",tools:["read_file","write_file","list_directory","file_info","search_files"],env:{MCP_ALLOWED_DIRS:"$HOME:/tmp"},key:false},{name:"database",package:"@mcp-hub/server-database",emoji:"🗄️",desc:"SQL query interface for SQLite",tools:["db_query","db_tables","db_schema","db_stats"],env:{MCP_DB_PATH:":memory:"},key:false},{name:"web-search",package:"@mcp-hub/server-web-search",emoji:"🔍",desc:"Web search via DuckDuckGo, page fetching",tools:["web_search","fetch_page"],key:false},{name:"datetime",package:"@mcp-hub/server-datetime",emoji:"📅",desc:"Timezone conversion, date calc, countdown",tools:["get_current_time","convert_timezone","calculate_date","countdown"],key:false},{name:"calculator",package:"@mcp-hub/server-calculator",emoji:"🔢",desc:"Math eval, unit conversion, hex/dec",tools:["calculate","convert_unit","hex_dec"],key:false},{name:"qrcode",package:"@mcp-hub/server-qrcode",emoji:"📱",desc:"Generate QR, WiFi, vCard codes",tools:["generate_qrcode","generate_wifi_qr","generate_vcard"],key:false},{name:"rss",package:"@mcp-hub/server-rss",emoji:"📡",desc:"Fetch/subscribe RSS/Atom feeds",tools:["fetch_feed","discover_feed"],key:false},{name:"memory",package:"@mcp-hub/server-memory",emoji:"🧠",desc:"Persistent key-value store with TTL and tags - AI context across sessions",tools:["memory_set","memory_get","memory_delete","memory_list","memory_tags"],key:false},{name:"fetch",package:"@mcp-hub/server-fetch",emoji:"🌐",desc:"Universal HTTP client - GET/POST/PUT/DELETE with headers",tools:["fetch","fetch_json","check_url"],key:false},{name:"code-runner",package:"@mcp-hub/server-code-runner",emoji:"🐍",desc:"Sandboxed Python/JS execution with timeout",tools:["run_code","run_python","run_javascript"],key:false}];
const G="\x1b[32m",B="\x1b[34m",Y="\x1b[33m",R="\x1b[31m",BD="\x1b[1m",RS="\x1b[0m";
function banner(){console.log("\n"+B+BD+"  🎯 MCP Server Hub v3"+RS+"\n"+B+"  "+"─".repeat(42)+RS+"\n  "+G+"AI Agent 原生工具链 - "+R.length+" servers"+RS+"\n")}
function claudePath(){const p=os.platform();if(p==="darwin")return path.join(os.homedir(),"Library/Application Support/Claude/claude_desktop_config.json");if(p==="win32")return path.join(process.env.APPDATA||"","Claude/claude_desktop_config.json");return path.join(os.homedir(),".config/Claude/claude_desktop_config.json")}
function cfg(s:any){const c:any={command:"npx",args:["-y",s.package]};if(s.env)c.env=s.env;return c}
function cmdList(){banner();console.log(BD+"Agent Tools:"+RS+"\n");const cats:any={};R.forEach((s:any)=>{const cat=s.key?"🔐 Needs API Key":s.tools[0].startsWith("memory")?"🧠 Context & Memory":s.tools[0].startsWith("fetch")||s.name==="web-search"||s.name==="rss"?"🌐 Network & Data":s.tools[0].includes("run_")||s.tools[0].includes("calculate")?"⚡ Compute & Execute":s.tools[0].includes("read_file")||s.tools[0].includes("db_")?"📁 Storage & Files":"🔧 Utilities";if(!cats[cat])cats[cat]=[];cats[cat].push(s)});Object.entries(cats).forEach(([cat,servers]:any)=>{console.log(Y+cat+RS);servers.forEach((s:any)=>console.log("  "+s.emoji+" "+BD+s.name.padEnd(16)+RS+s.desc));console.log()});console.log("─".repeat(50));console.log(BD+"Total: "+R.length+" servers"+RS);console.log("\n"+G+"npx mcp-server-hub config"+RS+" to generate Claude config\n")}
function cmdInfo(name:string){const s=R.find((x:any)=>x.name===name);if(!s){console.error(R+"Unknown: "+name+RS);process.exit(1)}console.log("\n"+BD+s.emoji+" "+s.name+RS+"\n"+B+"─".repeat(40)+RS+"\n📦 "+G+s.package+RS+"\n📝 "+s.desc+"\n\n"+BD+"Tools:"+RS);s.tools.forEach((t:any)=>console.log("  🔧 "+t));console.log("\n"+BD+"Config:"+RS);const c=cfg(s);console.log("  \""+s.name+"\": "+JSON.stringify(c,null,2).replace(/\n/g,"\n  "));if(s.env){console.log("\n"+Y+"Env:"+RS);Object.entries(s.env).forEach(([k,v]:any)=>console.log("  "+k+"="+v))}console.log()}
function cmdConfig(){const config:any={mcpServers:{}};R.filter((s:any)=>!s.key).forEach((s:any)=>{config.mcpServers[s.name]=cfg(s)});console.log("\n"+BD+"Claude Desktop Config"+RS+"\n"+B+"─".repeat(50)+RS+"\n\n"+Y+claudePath()+RS+":\n");console.log(JSON.stringify(config,null,2));console.log("\n"+G+"✅ "+Object.keys(config.mcpServers).length+" servers ready."+RS+"\n")}
function cmdHelp(){banner();console.log(BD+"Usage:"+RS+" npx mcp-server-hub <command>\n");console.log(BD+"Commands:"+RS);console.log("  "+G+"list"+RS+"              All "+R.length+" servers (grouped by category)");console.log("  "+G+"info <name>"+RS+"        Server details + config");console.log("  "+G+"config"+RS+"            Generate full Claude Desktop config");console.log("  "+G+"help"+RS+"              This help\n")}
const args=process.argv.slice(2);const cmd=args[0]||"help";const tgt=args[1];
switch(cmd){case"list":case"ls":cmdList();break;case"info":case"show":if(!tgt){console.error(R+"Usage: mcp-server-hub info <name>"+RS);process.exit(1)}cmdInfo(tgt);break;case"config":case"generate":cmdConfig();break;default:cmdHelp();}
