#!/usr/bin/env node
/**
 * 🗄️ MCP Database Server
 * SQL query interface for SQLite (read-only by default).
 */
import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam,getOptionalParam}from"@mcp-hub/shared";
const DB_PATH=process.env.MCP_DB_PATH||":memory:";const READONLY=process.env.MCP_DB_READONLY!=="false";
let db:any=null;
function getDB(){if(!db){try{const Database=require("better-sqlite3");db=new Database(DB_PATH,{readonly:READONLY});db.pragma("journal_mode=WAL")}catch(e){throw new Error(`Cannot open database:${e.message}. Install better-sqlite3: npm install better-sqlite3`)}}return db}
const server=new Server({name:"mcp-server-database",version:"1.0.0"},{capabilities:{tools:{}}});
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"db_query",description:"Execute a SELECT SQL query on the database.",inputSchema:{type:"object",properties:{sql:{type:"string",description:"SQL SELECT query"},limit:{type:"number",description:"Max rows to return (default:100)"}},required:["sql"]}},{name:"db_tables",description:"List all tables in the database.",inputSchema:{type:"object",properties:{}}},{name:"db_schema",description:"Show the schema (CREATE TABLE statement) for a table.",inputSchema:{type:"object",properties:{table:{type:"string",description:"Table name"}},required:["table"]}},{name:"db_stats",description:"Show database statistics (row counts, size).",inputSchema:{type:"object",properties:{}}}].concat(READONLY?[]:[{name:"db_execute",description:"Execute INSERT/UPDATE/DELETE/CREATE SQL (write mode enabled).",inputSchema:{type:"object",properties:{sql:{type:"string",description:"SQL statement to execute"}},required:["sql"]}}])}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;const d=getDB();switch(name){case"db_query":{const sql=requireParam(args,"sql");const limit=Number(args?.limit)||100;if(!/^\s*SELECT/i.test(sql))throw new Error("Only SELECT queries allowed. Use db_execute for writes.");const rows=d.prepare(sql).all();const limited=rows.slice(0,limit);if(!limited.length)return success(`📊 Query OK - 0 rows\nSQL:${sql}`);const cols=Object.keys(limited[0]);const lines=[`📊 Query Results (${Math.min(rows.length,limit)}/${rows.length} rows)`,"",cols.join(" | "),cols.map(()=>"---").join(" | ")];limited.forEach(r=>lines.push(cols.map(c=>String(r[c]??"NULL")).join(" | ")));if(rows.length>limit)lines.push(`... and ${rows.length-limit} more rows`);return success(lines.join("\n"))}
case"db_tables":{const rows=d.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all();const lines=[`📋 Tables (${rows.length}):`];rows.forEach((r:any,i:number)=>lines.push(`  ${i+1}. ${r.name}`));return success(lines.join("\n"))}
case"db_schema":{const table=requireParam(args,"table");const row=d.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(table);if(!row)return error(`Table not found:${table}`);return success(`📐 Schema:${table}\n\n${row.sql}`)}
case"db_stats":{const tables=d.prepare("SELECT name FROM sqlite_master WHERE type='table'").all();const lines=["📊 Database Statistics",`📁 Path:${DB_PATH}`,`🔒 Mode:${READONLY?"Read-only":"Read/Write"}`,""];for(const t of tables){const cnt=d.prepare(`SELECT COUNT(*) as c FROM "${t.name}"`).get();lines.push(`📋 ${t.name}:${cnt.c} rows`)}return success(lines.join("\n"))}
case"db_execute":{if(READONLY)return error("Database is in read-only mode. Set MCP_DB_READONLY=false to enable writes.");const sql=requireParam(args,"sql");const result=d.prepare(sql).run();return success(`✅ Executed OK\n📝 Changes:${result.changes}\n🆔 Last ID:${result.lastInsertRowid||"N/A"}`)}
default:return error(`Unknown tool:${name}`)}}catch(e){return error(e.message)}});
async function main(){const transport=new StdioServerTransport();await server.connect(transport);console.error(`🗄️ MCP Database Server running on stdio (${DB_PATH})`)}
main().catch(e=>{console.error("Fatal error:",e);process.exit(1)});